-- CREATE DE TODAS AS TABELAS DAS BASES SUBDOMINIO

-- 04 09 2014

-- ----------------------------------------------------------------------------------------
-- CREATES
-- ----------------------------------------------------------------------------------------



CREATE TABLE `CLIENTE` (
  `CLI_CD_CLIENTE` int(11) NOT NULL AUTO_INCREMENT,
  `CLI_NM_CLIENTE` varchar(45) NOT NULL,
  `CLI_DS_LOGRADOURO` varchar(45) DEFAULT NULL,
  `CLI_DS_BAIRRO` varchar(45) DEFAULT NULL,
  `CLI_DS_UF` varchar(2) DEFAULT NULL,
  `CLI_NR_TEL` varchar(45) DEFAULT NULL,
  `CLI_DS_ENTIDADE` varchar(45) NOT NULL,
  `CLI_CD_USUARIO` int(11) NOT NULL,
  `CLI_NR_CPF` varchar(45) DEFAULT NULL,
  `CLI_DS_REFERENCIA` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CLI_CD_CLIENTE`),
  KEY `CLI_CD_USUARIO_idx` (`CLI_CD_USUARIO`),
  KEY `idx_1` (`CLI_CD_CLIENTE`,`CLI_CD_USUARIO`,`CLI_DS_ENTIDADE`,`CLI_NM_CLIENTE`),
  KEY `idx_2` (`CLI_CD_CLIENTE`,`CLI_CD_USUARIO`,`CLI_NM_CLIENTE`),
  KEY `idx_3` (`CLI_CD_USUARIO`,`CLI_DS_ENTIDADE`,`CLI_NM_CLIENTE`),
  KEY `idx_4` (`CLI_CD_USUARIO`,`CLI_NM_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





CREATE TABLE `CONTA_PAGAR` (
  `COP_CD_CONTA_PAGAR` int(11) NOT NULL AUTO_INCREMENT,
  `COP_DS_CONTA_PAGAR` varchar(45) NOT NULL,
  `COP_DT_VENCIMENTO` date NOT NULL,
  `COP_VL_CONTA_PAGAR` double NOT NULL DEFAULT '0.01',
  `COP_DT_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COP_NR_DOCUMENTO` varchar(45) DEFAULT NULL,
  `COP_FL_PARCELADO` char(1) NOT NULL DEFAULT 'N',
  `COP_NR_PARCELA` int(11) NOT NULL DEFAULT '0',
  `COP_DS_FORNECEDOR` varchar(45) NOT NULL,
  `COP_FL_PAGO` char(1) NOT NULL DEFAULT 'N',
  `COP_DS_TIPO_CONTA` varchar(45) NOT NULL DEFAULT 'Outros',
  `COP_CD_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`COP_CD_CONTA_PAGAR`),
  KEY `idx_1` (`COP_DS_FORNECEDOR`),
  KEY `COP_CD_USUARIO_idx` (`COP_CD_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





CREATE TABLE `CONTA_RECEBER` (
  `COR_CD_CONTA_RECEBER` int(11) NOT NULL AUTO_INCREMENT,
  `COR_DS_CONTA_RECEBER` varchar(45) NOT NULL,
  `COR_DT_VENCIMENTO` date NOT NULL,
  `COR_VL_CONTA_RECEBER` double NOT NULL DEFAULT '0.01',
  `COR_DT_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COR_NR_DOCUMENTO` varchar(45) DEFAULT NULL,
  `COR_FL_PARCELADO` char(1) NOT NULL DEFAULT 'N',
  `COR_NR_PARCELA` int(11) NOT NULL DEFAULT '0',
  `COR_DS_FORNECEDOR` varchar(45) NOT NULL,
  `COR_FL_RECEBIDO` char(1) NOT NULL DEFAULT 'N',
  `COR_CD_USUARIO` int(11) NOT NULL,
  `COR_DS_TIPO_CONTA` varchar(45) NOT NULL DEFAULT 'Outros',
  PRIMARY KEY (`COR_CD_CONTA_RECEBER`),
  KEY `COR_CD_USUARIO_idx` (`COR_CD_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




CREATE TABLE `ENTIDADE` (
  `ENT_CD_ENTIDADE` int(11) NOT NULL AUTO_INCREMENT,
  `ENT_NM_ENTIDADE` varchar(45) NOT NULL,
  `ENT_CD_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ENT_CD_ENTIDADE`),
  KEY `ENT_CD_USUARIO_idx` (`ENT_CD_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





CREATE TABLE `FLUXO_CAIXA` (
  `FLU_CD_FLUXO_CAIXA` int(11) NOT NULL AUTO_INCREMENT,
  `FLU_DS_FLUXO_CAIXA` varchar(100) DEFAULT NULL,
  `FLU_CD_ENTIDADE` int(11) NOT NULL,
  `FLU_VL_FLUXO_CAIXA` float NOT NULL,
  `FLU_DT_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FLU_FL_TIPO` varchar(2) NOT NULL COMMENT 'EN = ENTRADA -- SA = SAIDA',
  `FLU_DS_FORMA_PAGAMENTO` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`FLU_CD_FLUXO_CAIXA`),
  KEY `FLU_CD_ENTIDADE_idx` (`FLU_CD_ENTIDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;





CREATE TABLE `FORMA_PAGAMENTO` (
  `FOP_CD_FORMA_PAGAMENTO` int(11) NOT NULL AUTO_INCREMENT,
  `FOP_DS_FORMA_PAGAMENTO` varchar(150) NOT NULL,
  `FOP_FL_TIPO` varchar(2) NOT NULL DEFAULT 'PR',
  PRIMARY KEY (`FOP_CD_FORMA_PAGAMENTO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





CREATE TABLE `FORNECEDOR` (
  `FOR_CD_FORNECEDOR` int(11) NOT NULL AUTO_INCREMENT,
  `FOR_DS_FORNECEDOR` varchar(45) NOT NULL,
  `FOR_NR_CNPJ` varchar(45) DEFAULT NULL,
  `FOR_CD_USUARIO` int(11) NOT NULL,
  `FOR_DS_LOGRADOURO` varchar(100) DEFAULT NULL,
  `FOR_DS_CIDADE` varchar(100) DEFAULT NULL,
  `FOR_DS_BAIRRO` varchar(100) DEFAULT NULL,
  `FOR_NR_CEP` varchar(45) DEFAULT NULL,
  `FOR_NR_INSC_ESTADUAL` varchar(100) DEFAULT NULL,
  `FOR_NR_INSC_MUNICIPAL` varchar(100) DEFAULT NULL,
  `FOR_DS_CONTATO` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`FOR_CD_FORNECEDOR`),
  KEY `FOR_CD_USUARIO_idx` (`FOR_CD_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





CREATE TABLE `ITEM_PROPOSTA` (
  `IPC_CD_ITEM_PROPOSTA` int(11) NOT NULL AUTO_INCREMENT,
  `IPC_CD_PROPOSTA_COMERCIAL` int(11) NOT NULL,
  `IPC_DS_ITEM_PROPOSTA` varchar(45) NOT NULL,
  `IPC_VL_ITEM_PROPOSTA` double NOT NULL,
  `IPC_NR_QUANTIDADE` double NOT NULL DEFAULT '1',
  `IPC_VL_DESCONTO` double NOT NULL DEFAULT '0',
  `IPC_DS_UNIDADE` varchar(4) NOT NULL DEFAULT 'UN',
  PRIMARY KEY (`IPC_CD_ITEM_PROPOSTA`),
  KEY `IPC_CD_PROPOSTA_COMERCIAL_idx` (`IPC_CD_PROPOSTA_COMERCIAL`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




CREATE TABLE `PARAMETRO` (
  `PAR_CD_PARAMETRO` int(11) NOT NULL AUTO_INCREMENT,
  `PAR_DS_PARAMETRO` varchar(45) NOT NULL,
  `PAR_VL_PARAMETRO` varchar(45) NOT NULL,
  `PAR_CD_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`PAR_CD_PARAMETRO`),
  KEY `PAR_CD_USUARIO_idx` (`PAR_CD_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




CREATE TABLE `PRODUTO` (
  `PRD_CD_PRODUTO` int(11) NOT NULL AUTO_INCREMENT,
  `PRD_DS_PRODUTO` varchar(45) NOT NULL,
  `PRD_VL_PRECO` float NOT NULL DEFAULT '0',
  `PRD_DS_UNIDADE` varchar(4) NOT NULL DEFAULT 'UN',
  `PRD_CD_USUARIO` int(11) NOT NULL,
  `PRD_NR_ESTOQUE` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`PRD_CD_PRODUTO`),
  KEY `idx_1` (`PRD_DS_PRODUTO`),
  KEY `PRD_CD_USUARIO_idx` (`PRD_CD_USUARIO`),
  KEY `idx_2` (`PRD_CD_PRODUTO`,`PRD_CD_USUARIO`,`PRD_DS_PRODUTO`),
  KEY `idx_3` (`PRD_CD_USUARIO`,`PRD_DS_PRODUTO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;




CREATE TABLE `PROPOSTA_COMERCIAL` (
  `PRC_CD_PROPOSTA_COMERCIAL` int(11) NOT NULL AUTO_INCREMENT,
  `PRC_CD_CLIENTE` int(11) DEFAULT NULL,
  `PRC_VL_DESCONTO` double NOT NULL DEFAULT '0',
  `PRC_VL_FRETE` double NOT NULL DEFAULT '0',
  `PRC_DT_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PRC_DT_PREVISTA` timestamp NULL DEFAULT NULL,
  `PRC_CD_USUARIO` int(11) NOT NULL,
  `PRC_DS_OBS` varchar(150) DEFAULT NULL,
  `PRC_NM_ATENDENTE` varchar(45) DEFAULT NULL,
  `PRC_DS_SITUACAO` varchar(100) DEFAULT NULL,
  `PRC_DS_FORMA_PAGAMENTO` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`PRC_CD_PROPOSTA_COMERCIAL`),
  KEY `PRC_CD_CLIENTE_idx` (`PRC_CD_CLIENTE`),
  KEY `PRC_CD_USUARIO_idx` (`PRC_CD_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





CREATE TABLE `SITUACAO_PROPOSTA` (
  `SIP_CD_SITUACAO_PROPOSTA` int(11) NOT NULL AUTO_INCREMENT,
  `SIP_DS_SITUACAO_PROPOSTA` varchar(100) NOT NULL,
  PRIMARY KEY (`SIP_CD_SITUACAO_PROPOSTA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




CREATE TABLE `SUBUSUARIO` (
  `SBU_CD_SUBUSUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `SBU_NM_SUBUSUARIO` varchar(45) NOT NULL,
  `SBU_DS_LOGIN` varchar(45) NOT NULL,
  `SBU_SH_SUBUSUARIO` varchar(45) NOT NULL,
  `SBU_CD_USUARIO` int(11) NOT NULL,
  `SBU_FL_MODULO_FINANCEIRO` varchar(1) NOT NULL DEFAULT 'N',
  `SBU_FL_MODULO_VENDA` varchar(1) NOT NULL DEFAULT 'N',
  `SBU_FL_ADM` varchar(1) NOT NULL DEFAULT 'N',
  `SBU_FL_MODULO_CLIENTE` varchar(1) NOT NULL DEFAULT 'N',
  `SBU_DS_MSG_FOOTER` varchar(100) DEFAULT ' ',
  `SBU_FL_MODULO_CAIXA` varchar(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`SBU_CD_SUBUSUARIO`),
  KEY `NAO_REPETIR` (`SBU_DS_LOGIN`),
  KEY `USU_CD_USUARIO_idx` (`SBU_CD_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;




CREATE TABLE `TIPO_CONTA` (
  `TCO_CD_TIPO_CONTA` int(11) NOT NULL AUTO_INCREMENT,
  `TCO_DS_TIPO_CONTA` varchar(45) NOT NULL,
  `TCO_CD_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`TCO_CD_TIPO_CONTA`),
  KEY `TCO_CD_USUARIO_idx` (`TCO_CD_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


