-- CREATE DO BANCO PRINCIPAL 

-- 04 09 2014

-- ----------------------------------------------------------------------------------------
-- CREATES
-- ----------------------------------------------------------------------------------------

CREATE TABLE `PARAMETRO` (
  `PAR_CD_PARAMETRO` int(11) NOT NULL AUTO_INCREMENT,
  `PAR_DS_PARAMETRO` varchar(45) NOT NULL,
  `PAR_VL_PARAMETRO` varchar(45) NOT NULL,
  `PAR_CD_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`PAR_CD_PARAMETRO`),
  KEY `PAR_CD_USUARIO_idx` (`PAR_CD_USUARIO`),
  CONSTRAINT `PAR_CD_USUARIO` FOREIGN KEY (`PAR_CD_USUARIO`) REFERENCES `USUARIO` (`USU_CD_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE `PLANO` (
  `PLA_CD_PLANO` int(11) NOT NULL,
  `PLA_DS_PLANO` varchar(150) NOT NULL,
  `PLA_NM_PLANO` varchar(45) NOT NULL,
  `PLA_DS_ESPACO` varchar(45) NOT NULL,
  PRIMARY KEY (`PLA_CD_PLANO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `USUARIO` (
  `USU_CD_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `USU_NM_USUARIO` varchar(45) NOT NULL,
  `USU_NR_CNPJ` varchar(45) NOT NULL,
  `USU_DS_EMAIL` varchar(45) NOT NULL,
  `USU_DS_SUBDOMINIO` varchar(100) NOT NULL DEFAULT 'processoErro.jsp',
  `USU_DS_FANTASIA` varchar(100) DEFAULT NULL,
  `USU_DS_LOGRADOURO` varchar(100) DEFAULT NULL,
  `USU_DS_NUMERO` varchar(45) DEFAULT NULL,
  `USU_DS_BAIRRO` varchar(100) DEFAULT NULL,
  `USU_DS_CIDADE` varchar(100) DEFAULT NULL,
  `USU_DS_UF` varchar(2) DEFAULT NULL,
  `USU_DS_TEL` varchar(45) DEFAULT NULL,
  `USU_CD_PLANO` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`USU_CD_USUARIO`),
  UNIQUE KEY `USU_NR_CNPJ_UNIQUE` (`USU_NR_CNPJ`),
  KEY `NAO_REPETIR` (`USU_NR_CNPJ`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;








